// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import structs "backend/apps/severino/src/structs"

// AlbumService is an autogenerated mock type for the AlbumService type
type AlbumService struct {
	mock.Mock
}

// Create provides a mock function with given fields: item
func (_m *AlbumService) Create(item interface{}) (interface{}, error) {
	ret := _m.Called(item)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: item
func (_m *AlbumService) Delete(item interface{}) (interface{}, error) {
	ret := _m.Called(item)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Publish provides a mock function with given fields: item
func (_m *AlbumService) Publish(item structs.Album) (structs.Album, error) {
	ret := _m.Called(item)

	var r0 structs.Album
	if rf, ok := ret.Get(0).(func(structs.Album) structs.Album); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Get(0).(structs.Album)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(structs.Album) error); ok {
		r1 = rf(item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields: search
func (_m *AlbumService) ReadAll(search structs.Search) (structs.Result, error) {
	ret := _m.Called(search)

	var r0 structs.Result
	if rf, ok := ret.Get(0).(func(structs.Search) structs.Result); ok {
		r0 = rf(search)
	} else {
		r0 = ret.Get(0).(structs.Result)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(structs.Search) error); ok {
		r1 = rf(search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadOne provides a mock function with given fields: item
func (_m *AlbumService) ReadOne(item interface{}) (interface{}, error) {
	ret := _m.Called(item)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unpublish provides a mock function with given fields: item
func (_m *AlbumService) Unpublish(item structs.Album) (structs.Album, error) {
	ret := _m.Called(item)

	var r0 structs.Album
	if rf, ok := ret.Get(0).(func(structs.Album) structs.Album); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Get(0).(structs.Album)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(structs.Album) error); ok {
		r1 = rf(item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: item
func (_m *AlbumService) Update(item interface{}) (interface{}, error) {
	ret := _m.Called(item)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
