// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import proto "backend/proto"

// PreferenceServiceServer is an autogenerated mock type for the PreferenceServiceServer type
type PreferenceServiceServer struct {
	mock.Mock
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *PreferenceServiceServer) Update(_a0 context.Context, _a1 *proto.PreferenceRequest) (*proto.PreferenceResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.PreferenceResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.PreferenceRequest) *proto.PreferenceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.PreferenceResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.PreferenceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
