// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import proto "backend/proto"

// ProductServiceServer is an autogenerated mock type for the ProductServiceServer type
type ProductServiceServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *ProductServiceServer) Create(_a0 context.Context, _a1 *proto.ProductRequest) (*proto.ProductResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.ProductResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ProductRequest) *proto.ProductResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ProductResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.ProductRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields: _a0, _a1
func (_m *ProductServiceServer) ReadAll(_a0 context.Context, _a1 *proto.SearchRequest) (*proto.ProductsResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.ProductsResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.SearchRequest) *proto.ProductsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ProductsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.SearchRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadOne provides a mock function with given fields: _a0, _a1
func (_m *ProductServiceServer) ReadOne(_a0 context.Context, _a1 *proto.ProductRequest) (*proto.ProductResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.ProductResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ProductRequest) *proto.ProductResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ProductResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.ProductRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *ProductServiceServer) Update(_a0 context.Context, _a1 *proto.ProductRequest) (*proto.ProductResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.ProductResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ProductRequest) *proto.ProductResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ProductResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.ProductRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
