// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import proto "backend/proto"

// TrackServiceServer is an autogenerated mock type for the TrackServiceServer type
type TrackServiceServer struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *TrackServiceServer) Create(_a0 context.Context, _a1 *proto.TrackRequest) (*proto.TrackResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.TrackResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.TrackRequest) *proto.TrackResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TrackResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.TrackRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *TrackServiceServer) Delete(_a0 context.Context, _a1 *proto.TrackRequest) (*proto.TrackResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.TrackResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.TrackRequest) *proto.TrackResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TrackResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.TrackRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields: _a0, _a1
func (_m *TrackServiceServer) ReadAll(_a0 context.Context, _a1 *proto.SearchRequest) (*proto.TracksResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.TracksResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.SearchRequest) *proto.TracksResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TracksResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.SearchRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadOne provides a mock function with given fields: _a0, _a1
func (_m *TrackServiceServer) ReadOne(_a0 context.Context, _a1 *proto.TrackRequest) (*proto.TrackResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.TrackResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.TrackRequest) *proto.TrackResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TrackResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.TrackRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *TrackServiceServer) Update(_a0 context.Context, _a1 *proto.TrackRequest) (*proto.TrackResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.TrackResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.TrackRequest) *proto.TrackResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TrackResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.TrackRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
