// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountsCustomError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountsCustomError) Reset()         { *m = AccountsCustomError{} }
func (m *AccountsCustomError) String() string { return proto.CompactTextString(m) }
func (*AccountsCustomError) ProtoMessage()    {}
func (*AccountsCustomError) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *AccountsCustomError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsCustomError.Unmarshal(m, b)
}
func (m *AccountsCustomError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsCustomError.Marshal(b, m, deterministic)
}
func (m *AccountsCustomError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsCustomError.Merge(m, src)
}
func (m *AccountsCustomError) XXX_Size() int {
	return xxx_messageInfo_AccountsCustomError.Size(m)
}
func (m *AccountsCustomError) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsCustomError.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsCustomError proto.InternalMessageInfo

func (m *AccountsCustomError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AccountsCustomError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailCode            string   `protobuf:"bytes,4,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	PhoneCode            string   `protobuf:"bytes,6,opt,name=phone_code,json=phoneCode,proto3" json:"phone_code,omitempty"`
	Active               bool     `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetEmailCode() string {
	if m != nil {
		return m.EmailCode
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPhoneCode() string {
	if m != nil {
		return m.PhoneCode
	}
	return ""
}

func (m *User) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type UserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total                int32    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UsersResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UsersResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *UsersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Account struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailCode            string   `protobuf:"bytes,4,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	PhoneCode            string   `protobuf:"bytes,6,opt,name=phone_code,json=phoneCode,proto3" json:"phone_code,omitempty"`
	CreatedAt            string   `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Exists               bool     `protobuf:"varint,8,opt,name=exists,proto3" json:"exists,omitempty"`
	UserId               string   `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{5}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetEmailCode() string {
	if m != nil {
		return m.EmailCode
	}
	return ""
}

func (m *Account) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Account) GetPhoneCode() string {
	if m != nil {
		return m.PhoneCode
	}
	return ""
}

func (m *Account) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Account) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *Account) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AccountRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{6}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AccountResponse struct {
	Account              *Account             `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Error                *AccountsCustomError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{7}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountResponse) GetError() *AccountsCustomError {
	if m != nil {
		return m.Error
	}
	return nil
}

type AccountsResponse struct {
	Accounts             []*Account           `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	Error                *AccountsCustomError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AccountsResponse) Reset()         { *m = AccountsResponse{} }
func (m *AccountsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountsResponse) ProtoMessage()    {}
func (*AccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{8}
}

func (m *AccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsResponse.Unmarshal(m, b)
}
func (m *AccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsResponse.Marshal(b, m, deterministic)
}
func (m *AccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsResponse.Merge(m, src)
}
func (m *AccountsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountsResponse.Size(m)
}
func (m *AccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsResponse proto.InternalMessageInfo

func (m *AccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *AccountsResponse) GetError() *AccountsCustomError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountsCustomError)(nil), "accounts.AccountsCustomError")
	proto.RegisterType((*User)(nil), "accounts.User")
	proto.RegisterType((*UserRequest)(nil), "accounts.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "accounts.UserResponse")
	proto.RegisterType((*UsersResponse)(nil), "accounts.UsersResponse")
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterType((*AccountRequest)(nil), "accounts.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "accounts.AccountResponse")
	proto.RegisterType((*AccountsResponse)(nil), "accounts.AccountsResponse")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x69, 0xfc, 0x93, 0x49, 0x09, 0xb0, 0xb4, 0xa9, 0x29, 0xaa, 0x14, 0x59, 0x1c, 0x22,
	0x21, 0x72, 0x48, 0x4f, 0x88, 0x03, 0x84, 0x88, 0x03, 0x07, 0x84, 0xb4, 0x11, 0x17, 0x2e, 0x91,
	0xb1, 0x47, 0xd4, 0x52, 0xec, 0x35, 0xde, 0x4d, 0x04, 0x15, 0x57, 0x9e, 0x80, 0x87, 0x44, 0xe2,
	0x29, 0xd0, 0xce, 0xee, 0x3a, 0x34, 0xcd, 0x01, 0x7a, 0xe8, 0xc9, 0x33, 0xf3, 0xcd, 0x37, 0x3b,
	0x33, 0xdf, 0xae, 0x61, 0x90, 0x66, 0x99, 0x58, 0x57, 0x4a, 0x4e, 0xea, 0x46, 0x28, 0xc1, 0x22,
	0xe7, 0x9f, 0x1e, 0x66, 0xa2, 0x2c, 0x45, 0x65, 0xe2, 0xc9, 0x1c, 0x1e, 0xce, 0x2c, 0x32, 0x5f,
	0x4b, 0x25, 0xca, 0x37, 0x4d, 0x23, 0x1a, 0xc6, 0xa0, 0x9b, 0x89, 0x1c, 0x63, 0x6f, 0xe4, 0x8d,
	0x7d, 0x4e, 0x36, 0x8b, 0x21, 0x2c, 0x51, 0xca, 0xf4, 0x33, 0xc6, 0x9d, 0x91, 0x37, 0xee, 0x71,
	0xe7, 0x26, 0xbf, 0x3d, 0xe8, 0x7e, 0x90, 0xd8, 0xb0, 0x01, 0x74, 0x8a, 0x9c, 0x48, 0x3d, 0xde,
	0x29, 0x72, 0x5d, 0xa6, 0x4a, 0x4b, 0x97, 0x4f, 0x36, 0x3b, 0x02, 0x1f, 0xcb, 0xb4, 0x58, 0xc5,
	0x07, 0x14, 0x34, 0x0e, 0x3b, 0x03, 0x20, 0x63, 0x49, 0xc7, 0x76, 0x09, 0xea, 0x51, 0x64, 0xae,
	0xcf, 0x3e, 0x02, 0xbf, 0xbe, 0x10, 0x15, 0xc6, 0xbe, 0x21, 0x91, 0xa3, 0x49, 0x64, 0x18, 0x52,
	0x60, 0x48, 0x14, 0x21, 0xd2, 0x10, 0x82, 0x34, 0x53, 0xc5, 0x06, 0xe3, 0x70, 0xe4, 0x8d, 0x23,
	0x6e, 0x3d, 0x4d, 0xcb, 0x1a, 0x4c, 0x15, 0xe6, 0xcb, 0x54, 0xc5, 0x91, 0xa1, 0xd9, 0xc8, 0x4c,
	0x69, 0x78, 0x5d, 0xe7, 0x0e, 0xee, 0x19, 0xd8, 0x46, 0x66, 0x2a, 0x99, 0x41, 0x5f, 0xcf, 0xca,
	0xf1, 0xcb, 0x1a, 0xa5, 0x62, 0x09, 0x74, 0xd7, 0x12, 0x1b, 0x1a, 0xba, 0x3f, 0x1d, 0x4c, 0xda,
	0xbd, 0x53, 0x12, 0x61, 0x76, 0x2d, 0x1d, 0xb7, 0x96, 0x64, 0x0a, 0x87, 0xa6, 0x84, 0xac, 0x45,
	0x25, 0xf1, 0x5f, 0x6a, 0x24, 0xdf, 0xe1, 0xae, 0xf6, 0x64, 0x4b, 0x7a, 0x02, 0xbe, 0x06, 0x64,
	0xec, 0x8d, 0x0e, 0xf6, 0xb0, 0x0c, 0xa8, 0x15, 0xa8, 0x9d, 0x62, 0x3e, 0x27, 0x9b, 0x3d, 0x86,
	0x9e, 0xfe, 0x2e, 0x65, 0x71, 0x89, 0xa4, 0x82, 0xcf, 0x23, 0x1d, 0x58, 0x14, 0x97, 0xb4, 0x69,
	0x25, 0x54, 0xba, 0x22, 0x0d, 0x7c, 0x6e, 0x9c, 0xe4, 0x97, 0x07, 0xa1, 0xbd, 0x27, 0xfb, 0x44,
	0x56, 0xdf, 0xea, 0x56, 0x64, 0x6d, 0xdf, 0xa2, 0xc8, 0x57, 0xc5, 0x0c, 0x77, 0xc5, 0x1c, 0x42,
	0x80, 0x5f, 0x0b, 0xa9, 0x24, 0xe9, 0x1c, 0x71, 0xeb, 0xb1, 0x13, 0x08, 0xf5, 0x82, 0x96, 0x45,
	0x6e, 0x15, 0x0e, 0xb4, 0xfb, 0x36, 0x4f, 0xde, 0xc1, 0xc0, 0x0e, 0xea, 0x14, 0x7e, 0xda, 0x8e,
	0x6e, 0x05, 0x7a, 0xb0, 0x5d, 0xb5, 0x4b, 0xdd, 0x59, 0xce, 0x56, 0x6a, 0x09, 0xf7, 0xda, 0x72,
	0x56, 0xb8, 0xff, 0xaa, 0x77, 0x0e, 0x3e, 0xea, 0x17, 0x49, 0x25, 0xfb, 0xd3, 0xb3, 0x6b, 0xa9,
	0x7f, 0x3f, 0x5b, 0x6e, 0x72, 0x93, 0x0d, 0xdc, 0x77, 0x68, 0x7b, 0xea, 0x33, 0x88, 0x5c, 0xcc,
	0xde, 0x98, 0x3d, 0xc7, 0xb6, 0x29, 0x37, 0x3a, 0x77, 0xfa, 0xc3, 0x33, 0x6f, 0x63, 0x81, 0xcd,
	0xa6, 0xc8, 0x90, 0x3d, 0x87, 0x60, 0x4e, 0x4a, 0xb0, 0xe3, 0x9d, 0xdb, 0x69, 0x56, 0x7b, 0x3a,
	0xdc, 0x0d, 0x9b, 0x66, 0x93, 0x3b, 0xec, 0x05, 0x84, 0x1c, 0xd3, 0x7c, 0xb6, 0x5a, 0xb1, 0xe3,
	0x89, 0xfd, 0x63, 0x2d, 0x30, 0x6d, 0xb2, 0x0b, 0xc7, 0x3d, 0xb9, 0xca, 0x95, 0x5b, 0xf2, 0xf4,
	0xa7, 0xd7, 0x8a, 0xe8, 0x5a, 0x79, 0xd9, 0xb6, 0x12, 0x5f, 0x1f, 0xdb, 0x56, 0x7c, 0xb4, 0x07,
	0x69, 0x1b, 0x7a, 0x65, 0x1a, 0x7a, 0x5f, 0xdd, 0xb4, 0xc2, 0xeb, 0xf0, 0xa3, 0x4f, 0xff, 0xdc,
	0x4f, 0x01, 0x7d, 0xce, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x84, 0x5e, 0x75, 0x87, 0xa4, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	ReadAll(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*UsersResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/accounts.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadAll(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/accounts.UserService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *UserRequest) (*UserResponse, error)
	ReadAll(context.Context, *SearchRequest) (*UsersResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.UserService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadAll(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _UserService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts.proto",
}

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Create(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
	ReadOne(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Create(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ReadOne(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountResponse, error) {
	out := new(AccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/ReadOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Create(context.Context, *AccountRequest) (*AccountResponse, error)
	ReadOne(context.Context, *AccountRequest) (*AccountResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ReadOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ReadOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/ReadOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ReadOne(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "ReadOne",
			Handler:    _AccountService_ReadOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts.proto",
}
