// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pagination struct {
	PerPage              int32    `protobuf:"varint,1,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Offset               int32    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Order                string   `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	SortBy               string   `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Total                int32    `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Pagination) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Pagination) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *Pagination) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *Pagination) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Search struct {
	Pagination           *Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Raw                  string      `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	Extra                string      `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Search) Reset()         { *m = Search{} }
func (m *Search) String() string { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()    {}
func (*Search) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{1}
}

func (m *Search) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Search.Unmarshal(m, b)
}
func (m *Search) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Search.Marshal(b, m, deterministic)
}
func (m *Search) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Search.Merge(m, src)
}
func (m *Search) XXX_Size() int {
	return xxx_messageInfo_Search.Size(m)
}
func (m *Search) XXX_DiscardUnknown() {
	xxx_messageInfo_Search.DiscardUnknown(m)
}

var xxx_messageInfo_Search proto.InternalMessageInfo

func (m *Search) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *Search) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

func (m *Search) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

type SearchRequest struct {
	Search               *Search  `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{2}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetSearch() *Search {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *SearchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Pagination)(nil), "common.Pagination")
	proto.RegisterType((*Search)(nil), "common.Search")
	proto.RegisterType((*SearchRequest)(nil), "common.SearchRequest")
}

func init() { proto.RegisterFile("proto/common.proto", fileDescriptor_1747d3070a2311a0) }

var fileDescriptor_1747d3070a2311a0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0x95, 0xb4, 0x71, 0xc8, 0x22, 0x2a, 0xb4, 0x42, 0x60, 0x6e, 0x55, 0x0e, 0xa8, 0xa7,
	0x22, 0x95, 0x37, 0xe8, 0x85, 0x6b, 0x65, 0x6e, 0x5c, 0x2a, 0xb7, 0xd9, 0x86, 0x48, 0x34, 0x36,
	0x1b, 0x23, 0xe8, 0x9b, 0xf0, 0xb8, 0x28, 0x6b, 0xf3, 0x73, 0xf2, 0x7e, 0xe3, 0xd1, 0xce, 0xd8,
	0x80, 0x9e, 0x5d, 0x70, 0xf7, 0x7b, 0x77, 0x3c, 0xba, 0x7e, 0x29, 0x80, 0x2a, 0x52, 0xfd, 0x95,
	0x01, 0x6c, 0x6c, 0xdb, 0xf5, 0x36, 0x74, 0xae, 0xc7, 0x5b, 0x38, 0xf3, 0xc4, 0x5b, 0x6f, 0x5b,
	0xd2, 0xd9, 0x3c, 0x5b, 0x14, 0xa6, 0xf4, 0xc4, 0x1b, 0xdb, 0x12, 0x22, 0x4c, 0x45, 0xce, 0x45,
	0x96, 0x19, 0xaf, 0x41, 0xb9, 0xc3, 0x61, 0xa0, 0xa0, 0x27, 0xa2, 0x26, 0xc2, 0x2b, 0x28, 0x1c,
	0x37, 0xc4, 0x7a, 0x3a, 0xcf, 0x16, 0x95, 0x89, 0x80, 0x37, 0x50, 0x0e, 0x8e, 0xc3, 0x76, 0x77,
	0xd2, 0x85, 0xe8, 0x6a, 0xc4, 0xf5, 0x69, 0xb4, 0x07, 0x17, 0xec, 0xab, 0x56, 0xb2, 0x25, 0x42,
	0xdd, 0x80, 0x7a, 0x22, 0xcb, 0xfb, 0x17, 0x5c, 0x01, 0xf8, 0xdf, 0x8e, 0xd2, 0xeb, 0x7c, 0x85,
	0xcb, 0xf4, 0x9e, 0xbf, 0xf6, 0xe6, 0x9f, 0x0b, 0x2f, 0x61, 0xc2, 0xf6, 0x43, 0xda, 0x56, 0x66,
	0x1c, 0xc7, 0x14, 0xfa, 0x0c, 0x6c, 0xa5, 0x6b, 0x65, 0x22, 0xd4, 0x8f, 0x70, 0x11, 0x53, 0x0c,
	0xbd, 0xbd, 0xd3, 0x10, 0xf0, 0x0e, 0xd4, 0x20, 0x42, 0x0a, 0x9a, 0xfd, 0x04, 0x25, 0x5b, 0xba,
	0xc5, 0x19, 0xe4, 0x5d, 0x93, 0xf6, 0xe7, 0x5d, 0xb3, 0x2e, 0x9f, 0x0b, 0xf9, 0xda, 0x9d, 0x92,
	0xe3, 0xe1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x94, 0x17, 0xfd, 0x3c, 0x77, 0x01, 0x00, 0x00,
}
