// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ecommerce.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            string         `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string         `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedSellingAt     string         `protobuf:"bytes,4,opt,name=started_selling_at,json=startedSellingAt,proto3" json:"started_selling_at,omitempty"`
	FinishedSellingAt    string         `protobuf:"bytes,5,opt,name=finished_selling_at,json=finishedSellingAt,proto3" json:"finished_selling_at,omitempty"`
	UsageExpiresAt       string         `protobuf:"bytes,6,opt,name=usage_expires_at,json=usageExpiresAt,proto3" json:"usage_expires_at,omitempty"`
	Name                 string         `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Stock                int32          `protobuf:"varint,9,opt,name=stock,proto3" json:"stock,omitempty"`
	Sku                  uint64         `protobuf:"varint,10,opt,name=sku,proto3" json:"sku,omitempty"`
	Image                string         `protobuf:"bytes,11,opt,name=image,proto3" json:"image,omitempty"`
	IsPublished          bool           `protobuf:"varint,12,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	Company              string         `protobuf:"bytes,13,opt,name=company,proto3" json:"company,omitempty"`
	ProductType          string         `protobuf:"bytes,14,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	Items                string         `protobuf:"bytes,15,opt,name=items,proto3" json:"items,omitempty"`
	PaymentsTypes        []*PaymentType `protobuf:"bytes,16,rep,name=payments_types,json=paymentsTypes,proto3" json:"payments_types,omitempty"`
	History              string         `protobuf:"bytes,17,opt,name=history,proto3" json:"history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba438465af3fc23, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Product) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Product) GetStartedSellingAt() string {
	if m != nil {
		return m.StartedSellingAt
	}
	return ""
}

func (m *Product) GetFinishedSellingAt() string {
	if m != nil {
		return m.FinishedSellingAt
	}
	return ""
}

func (m *Product) GetUsageExpiresAt() string {
	if m != nil {
		return m.UsageExpiresAt
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetStock() int32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Product) GetSku() uint64 {
	if m != nil {
		return m.Sku
	}
	return 0
}

func (m *Product) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Product) GetIsPublished() bool {
	if m != nil {
		return m.IsPublished
	}
	return false
}

func (m *Product) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Product) GetProductType() string {
	if m != nil {
		return m.ProductType
	}
	return ""
}

func (m *Product) GetItems() string {
	if m != nil {
		return m.Items
	}
	return ""
}

func (m *Product) GetPaymentsTypes() []*PaymentType {
	if m != nil {
		return m.PaymentsTypes
	}
	return nil
}

func (m *Product) GetHistory() string {
	if m != nil {
		return m.History
	}
	return ""
}

type PaymentType struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Installments         int32    `protobuf:"varint,4,opt,name=installments,proto3" json:"installments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentType) Reset()         { *m = PaymentType{} }
func (m *PaymentType) String() string { return proto.CompactTextString(m) }
func (*PaymentType) ProtoMessage()    {}
func (*PaymentType) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba438465af3fc23, []int{1}
}

func (m *PaymentType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentType.Unmarshal(m, b)
}
func (m *PaymentType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentType.Marshal(b, m, deterministic)
}
func (m *PaymentType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentType.Merge(m, src)
}
func (m *PaymentType) XXX_Size() int {
	return xxx_messageInfo_PaymentType.Size(m)
}
func (m *PaymentType) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentType.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentType proto.InternalMessageInfo

func (m *PaymentType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentType) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PaymentType) GetInstallments() int32 {
	if m != nil {
		return m.Installments
	}
	return 0
}

type ProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductRequest) Reset()         { *m = ProductRequest{} }
func (m *ProductRequest) String() string { return proto.CompactTextString(m) }
func (*ProductRequest) ProtoMessage()    {}
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba438465af3fc23, []int{2}
}

func (m *ProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRequest.Unmarshal(m, b)
}
func (m *ProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRequest.Marshal(b, m, deterministic)
}
func (m *ProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRequest.Merge(m, src)
}
func (m *ProductRequest) XXX_Size() int {
	return xxx_messageInfo_ProductRequest.Size(m)
}
func (m *ProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRequest proto.InternalMessageInfo

func (m *ProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type ProductResponse struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductResponse) Reset()         { *m = ProductResponse{} }
func (m *ProductResponse) String() string { return proto.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()    {}
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba438465af3fc23, []int{3}
}

func (m *ProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductResponse.Unmarshal(m, b)
}
func (m *ProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductResponse.Marshal(b, m, deterministic)
}
func (m *ProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductResponse.Merge(m, src)
}
func (m *ProductResponse) XXX_Size() int {
	return xxx_messageInfo_ProductResponse.Size(m)
}
func (m *ProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductResponse proto.InternalMessageInfo

func (m *ProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type ProductsResponse struct {
	Products             []*Product  `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProductsResponse) Reset()         { *m = ProductsResponse{} }
func (m *ProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ProductsResponse) ProtoMessage()    {}
func (*ProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba438465af3fc23, []int{4}
}

func (m *ProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductsResponse.Unmarshal(m, b)
}
func (m *ProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductsResponse.Marshal(b, m, deterministic)
}
func (m *ProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductsResponse.Merge(m, src)
}
func (m *ProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ProductsResponse.Size(m)
}
func (m *ProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProductsResponse proto.InternalMessageInfo

func (m *ProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *ProductsResponse) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "ecommerce.Product")
	proto.RegisterType((*PaymentType)(nil), "ecommerce.PaymentType")
	proto.RegisterType((*ProductRequest)(nil), "ecommerce.ProductRequest")
	proto.RegisterType((*ProductResponse)(nil), "ecommerce.ProductResponse")
	proto.RegisterType((*ProductsResponse)(nil), "ecommerce.ProductsResponse")
}

func init() { proto.RegisterFile("ecommerce.proto", fileDescriptor_4ba438465af3fc23) }

var fileDescriptor_4ba438465af3fc23 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4f, 0x8f, 0xd3, 0x3e,
	0x10, 0xfd, 0x25, 0xdb, 0x6c, 0xda, 0x49, 0xb7, 0xed, 0xfa, 0xb7, 0x20, 0x53, 0x84, 0x14, 0x72,
	0xca, 0x01, 0xf5, 0x50, 0xce, 0xb0, 0xca, 0x22, 0xce, 0x54, 0x29, 0x5c, 0xb8, 0x54, 0xde, 0xc4,
	0xb4, 0x56, 0xf3, 0xc7, 0xc4, 0xce, 0x8a, 0x7e, 0x16, 0x6e, 0x7c, 0x52, 0xe4, 0x3f, 0x49, 0xbb,
	0xda, 0x5e, 0x80, 0x53, 0x3d, 0xef, 0xbd, 0x79, 0x33, 0x9e, 0x8e, 0x03, 0x53, 0x9a, 0xd5, 0x65,
	0x49, 0x9b, 0x8c, 0x2e, 0x78, 0x53, 0xcb, 0x1a, 0x8d, 0x7a, 0x60, 0x3e, 0x56, 0xa7, 0xba, 0x32,
	0x44, 0xf4, 0x6b, 0x00, 0xfe, 0xaa, 0xa9, 0xf3, 0x36, 0x93, 0x68, 0x02, 0x2e, 0xcb, 0xb1, 0x13,
	0x3a, 0xf1, 0x28, 0x75, 0x59, 0x8e, 0x5e, 0x01, 0x64, 0x0d, 0x25, 0x92, 0xe6, 0x1b, 0x22, 0xb1,
	0xab, 0xf1, 0x91, 0x45, 0x12, 0xa9, 0xe8, 0x96, 0xe7, 0x1d, 0x7d, 0x61, 0x68, 0x8b, 0x24, 0x12,
	0xbd, 0x01, 0x24, 0x24, 0x69, 0x14, 0x2d, 0x68, 0x51, 0xb0, 0x6a, 0xab, 0x64, 0x03, 0x2d, 0x9b,
	0x59, 0x66, 0x6d, 0x88, 0x44, 0xa2, 0x05, 0xfc, 0xff, 0x8d, 0x55, 0x4c, 0xec, 0x1e, 0xcb, 0x3d,
	0x2d, 0xbf, 0xee, 0xa8, 0xa3, 0x3e, 0x86, 0x59, 0x2b, 0xc8, 0x96, 0x6e, 0xe8, 0x0f, 0xce, 0x1a,
	0x2a, 0x94, 0xf8, 0x52, 0x8b, 0x27, 0x1a, 0xff, 0x68, 0xe0, 0x44, 0x22, 0x04, 0x83, 0x8a, 0x94,
	0x14, 0xfb, 0x9a, 0xd5, 0x67, 0x14, 0x42, 0x90, 0x53, 0x91, 0x35, 0x8c, 0x4b, 0x56, 0x57, 0x78,
	0xa8, 0xa9, 0x53, 0x08, 0xdd, 0x80, 0x27, 0x64, 0x9d, 0xed, 0xf1, 0x28, 0x74, 0x62, 0x2f, 0x35,
	0x01, 0x9a, 0xc1, 0x85, 0xd8, 0xb7, 0x18, 0x42, 0x27, 0x1e, 0xa4, 0xea, 0xa8, 0x74, 0xac, 0x24,
	0x5b, 0x8a, 0x03, 0xed, 0x61, 0x02, 0xf4, 0x1a, 0xc6, 0x4c, 0x6c, 0x78, 0x7b, 0x5f, 0xe8, 0xb6,
	0xf1, 0x38, 0x74, 0xe2, 0x61, 0x1a, 0x30, 0xb1, 0xea, 0x20, 0x84, 0xc1, 0xcf, 0xea, 0x92, 0x93,
	0xea, 0x80, 0xaf, 0x74, 0x6a, 0x17, 0xaa, 0x64, 0x6e, 0xfe, 0x91, 0x8d, 0x3c, 0x70, 0x8a, 0x27,
	0xa6, 0x3b, 0x8b, 0x7d, 0x3e, 0x70, 0xaa, 0xab, 0x4a, 0x5a, 0x0a, 0x3c, 0xb5, 0x55, 0x55, 0x80,
	0xde, 0xc1, 0x84, 0x93, 0x43, 0x49, 0x2b, 0x29, 0x74, 0xa6, 0xc0, 0xb3, 0xf0, 0x22, 0x0e, 0x96,
	0xcf, 0x17, 0xc7, 0x75, 0x58, 0x19, 0x81, 0x72, 0x49, 0xaf, 0x3a, 0xb5, 0x8a, 0x84, 0xea, 0x68,
	0xc7, 0x84, 0xac, 0x9b, 0x03, 0xbe, 0x36, 0x1d, 0xd9, 0x30, 0xda, 0x43, 0x70, 0x92, 0xf7, 0x64,
	0x4f, 0xba, 0x09, 0xbb, 0x27, 0x13, 0xbe, 0x01, 0x8f, 0x37, 0x2c, 0xa3, 0x7a, 0x2f, 0xbc, 0xd4,
	0x04, 0x28, 0x82, 0x31, 0xab, 0x84, 0x24, 0x45, 0xa1, 0xeb, 0xea, 0x6d, 0xf0, 0xd2, 0x47, 0x58,
	0xf4, 0x1e, 0x26, 0x76, 0x21, 0x53, 0xfa, 0xbd, 0xa5, 0x42, 0x6d, 0x92, 0x6f, 0x2f, 0xaf, 0x8b,
	0x06, 0x4b, 0x74, 0x7a, 0x21, 0xab, 0xed, 0x24, 0xd1, 0x2d, 0x4c, 0xfb, 0x7c, 0xc1, 0xeb, 0x4a,
	0xd0, 0x3f, 0x34, 0x78, 0x80, 0x99, 0xc5, 0x44, 0xef, 0xb0, 0x80, 0xa1, 0xa5, 0x05, 0x76, 0xf4,
	0x50, 0xcf, 0x59, 0xf4, 0x1a, 0xb4, 0x04, 0xe0, 0x64, 0xcb, 0x2a, 0xa2, 0xf7, 0xcb, 0xb5, 0x45,
	0xed, 0xcb, 0x5b, 0xf5, 0x4c, 0x7a, 0xa2, 0x5a, 0xfe, 0x74, 0xfb, 0x9b, 0xaf, 0x69, 0xf3, 0xa0,
	0xe6, 0x95, 0xc0, 0xe5, 0x07, 0xfd, 0xde, 0xd0, 0x8b, 0x33, 0xe5, 0xcc, 0x78, 0xe6, 0xf3, 0x73,
	0x94, 0xe9, 0x3b, 0xfa, 0x4f, 0x59, 0x7c, 0xd1, 0x6f, 0xf2, 0xef, 0x2d, 0xee, 0xc0, 0x4f, 0x29,
	0xc9, 0x3f, 0x55, 0xff, 0xe0, 0x71, 0x6b, 0x3c, 0x92, 0xa2, 0x40, 0xcf, 0xba, 0x39, 0xac, 0x29,
	0x69, 0xb2, 0x5d, 0x97, 0xff, 0xf2, 0x69, 0xbe, 0x38, 0x1a, 0xdc, 0xf9, 0x5f, 0x3d, 0xfd, 0xc5,
	0xba, 0xbf, 0xd4, 0x3f, 0x6f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x8b, 0x5e, 0xae, 0xe4,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductServiceClient interface {
	Create(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	Update(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	ReadOne(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	ReadAll(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ProductsResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) Create(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/ecommerce.ProductService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) Update(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/ecommerce.ProductService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ReadOne(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, "/ecommerce.ProductService/ReadOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) ReadAll(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*ProductsResponse, error) {
	out := new(ProductsResponse)
	err := c.cc.Invoke(ctx, "/ecommerce.ProductService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductServiceServer is the server API for ProductService service.
type ProductServiceServer interface {
	Create(context.Context, *ProductRequest) (*ProductResponse, error)
	Update(context.Context, *ProductRequest) (*ProductResponse, error)
	ReadOne(context.Context, *ProductRequest) (*ProductResponse, error)
	ReadAll(context.Context, *SearchRequest) (*ProductsResponse, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.ProductService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Create(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.ProductService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).Update(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ReadOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ReadOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.ProductService/ReadOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ReadOne(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ecommerce.ProductService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).ReadAll(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductService_Update_Handler,
		},
		{
			MethodName: "ReadOne",
			Handler:    _ProductService_ReadOne_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _ProductService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecommerce.proto",
}
